### ISSUE TITLE
🚀 FEAT: Add database folder when creating new project

### ISSUE THREAD

**Issue by Mackignacio** [mayajs/cli#19]
## 📝 Description

As of the new update where mayajs can handle multiple database. We need to organize our folder structure to have a separate folder for the databases. I suggest to create this folder when `maya new` command is executed.

## ⚙️ Component
- cli

## 📋 Todo:

- [x] Create a task runner for creating database folder
- [x] Create a basic database file default mongo
- [x] Add task to `maya new` command
